services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/sleepr
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/sleepr
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
